import os

UPLOAD_FOLDER = os.getcwd()
UPLOAD_FOLDER_NAME = 'UPLOAD_FOLDER'
REQUEST_ID = "REQUEST_ID"
ENTITIES = 'ENTITIES'
ALLOWED_EXTENSIONS = {'zip'}
COMPANY_HTML_DIRECTORY = 'company_page'
PROFILE_HTML_DIRECTORY = 'profile_html'
SLASH = '/'
WRITE_MODE = 'w'
READ_MODE = 'r'
UNDERSCORE = '_'
DOT = '.'
SPACE = " "
BLANK = ""
S3='s3'
CONTENTS = 'Contents'
KEY = 'Key'
COMPANY_JSON_DIRECTORY = 'company_json'
FINAL_JSON_DIRECTORY = 'final_json'
PROFILE_JSON_DIRECTORY = "profile_json"+SLASH
ZIP_EXTRACT_DIRECTORY = 'profile_html'+SLASH
SUCCESS = "success"
POST_PROCESSING_ERROR = 'error in Post Processing.... please check'
UPLOAD_ERROR = 'upload error......check file type, should be a zip file'
DESTINATION_DIRECTORY = 'profile_html'
COMPANY = 'company'
PROFILE = 'ProfileHtml'
MOVE_SOURCE = os.getcwd()+ SLASH + ZIP_EXTRACT_DIRECTORY + COMPANY
MOVE_DESTINATION = os.getcwd() + SLASH + COMPANY_HTML_DIRECTORY + SLASH
ASSETS_DIRECTORY = 'assets'
COMPLETE = 'complete'
ERROR = 'error'
DS_STORE = '.DS_Store'
ALL_JSON_FILES = '*.json'
ALL_HTML_FILES = '*.html'
ALL_MOBILE_HTML_FILES = '*.mhtml'
ALL_TYPE_HTML_FILES = '*html'
ALL_ZIP_FILES = '*.zip'
ZIP_EXTENSION = '.zip'
HTML_PREFIX = 'Html_'
FILE = 'file'
POST_METHOD = 'POST'
JSON_EXTENSION = '.json'
LOCAL_SOURCE_LINKEDIN = 'LOCAL_SOURCE_LINKEDIN_'
MERGING_JSON_DATA = 'merging_json_data'
NO_FILE_FOUND = 'no file found'
UNABLE_TO_FIND = 'unable to find file with the given requestID'
COMPANY_CRAWL_STATUS = 'CompanyCrawlStatus.json'
COMPLETE_STATUS = "COMPLETE"
CRAWLING_STATUS = "CRAWLING"
SCHEDULED_STATUS = "SCHEDULED"
PICKED_STATUS = 'PICKED'
REQUEST_ID = 'REQUEST_ID'
STATUS = 'STATUS'
COMPANY_NAMES = "COMPANY_NAMES"
REMOVE_COMPANY_LIST = ["Freelance", "Consultancy","_ ","..","...","...."]
LATEST_ORGANIZATION = "latest_organization"
LATEST_INDUSTRY_TYPE = 'latest_industry_type'
WEBSITE = 'website'
WORK_DETAILS = "work_details"
IS_LATEST = "is_latest"
EMPLOYEE_COUNT = "employee_count"
INDUSTRY = "industry"
WEBSITE_URL = "website_url"
LATEST_COMPANY_SIZE = 'latest_company_size'
STATUS_JSON = 'status.json'
NONETYPE = "NoneType"
FILENAME = "FILENAME"
DATA = "DATA"
LAST_MODIFIED = "LastModified"
NAME = "name"
AUTOMATE_POST_LOGGER = "automatePostLogger"
AUTOMATE_PROCESSING_LOGS = "automateProfileProcessing.log"
COMPANY_LOGGER = "companyLogger"
COMPANY_LOGGER_LOGS = "companyProcessingLogs.log"
PROFILE_LOGGER = "profileLogger"
PROFILE_LOGGER_LOGS = "ProfileProcessingLogs.log"
BATCH_LOGGER = 'batchlogger'
BATCH_LOGGER_LOGS = "batchProcessingLogs.log"
S3LOGGER = 's3logger'
S3_PROCESSING_LOGS = "s3ProcessingLogs.log"
